### ISSUE TITLE
Editor styling adds too much padding

### ISSUE THREAD

**Issue by Clorith** [afragen/handbook-callout-blocks#3]
Within the editor it self, the callouts have increased padding on the innerblocks. This is caused by the blockeditors default styling for paragraph blocks taking priority within the innerblock wrappers.

Editor view:
![image](https://user-images.githubusercontent.com/468735/187794352-1eaba06c-ae2d-43ab-9396-3c819e3a2e42.png)

Front-end view:
![image](https://user-images.githubusercontent.com/468735/187794255-81ece946-70c0-45ec-9448-5918317f5cce.png)

**Comment by afragen** [comment]
Interesting as I added that because originally it didn't add enough in the editor. I made them the same.

**Comment by afragen** [comment]
https://github.com/afragen/handbook-callout-blocks/commit/b1ae81b4b829722795536578e6aabc93d464a657

**Comment by afragen** [comment]
Should be fixed now.
